service: school-ticket-sales-service-discovery

provider:
  name: google
  runtime: nodejs
  project: school-ticket-sales
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions
  - serverless-plugin-typescript

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  createEndpoint:
    handler: createEndpoint
    events:
      - http: path
  flipEndpoint:
    handler: flipEndpoint
    events:
      - http: path
  getEndpoints:
    handler: getEndpoints
    events:
      - http: path
